//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_PropertyManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Report
    {
        public int ReportID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> ManagerID { get; set; }

        [Required]
        [MaxLength(200)]
        public string ReportBody { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
    
        public virtual PropertyManager PropertyManager { get; set; }
        public virtual PropertyOwner PropertyOwner { get; set; }
    }
}
